source 'https://rubygems.org'
### gem 'rails'
gem 'sinatra'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'pg'
#gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem 'tux'
gem 'rack-flash3'
gem 'sinatra-flash'
gem 'require_all', '~> 1.5'
gem 'dotenv'